version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    env_file: .env
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    env_file: .env
    image: qualityru/kittygram_backend
    volumes:
      - static:/backend_static/
      - media:/media/
    depends_on:
      - db
  frontend:
    env_file: .env
    image: qualityru/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/
  gateway:
    env_file: .env
    image: qualityru/kittygram_gateway
    ports:
      - 9000:80
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - backend
